### ISSUE TITLE
Implementation of max ranks or a "career" system

### ISSUE THREAD

**Issue by Dubjunk** [Wyqer/KP_Ranks#7]
## Feature request

The idea is, to add a limitation for the reachable Rank, so that you can reserve for Admins (for example).

This could be implemented by assigning a maximum rank for the players and admins.

A much prettier way would be the implementation of a "career" system.

For the German Army like listed in the wiki below:
https://en.wikipedia.org/wiki/Ranks_of_the_German_Bundeswehr#Enlisted_personnel

So there could be a limitation based on your personal "status".

If i'm listed as _Non-commissioned Officers "with swordknot"_ i can reach everything until _OR-9_.

**Comment by Wyqer** [comment]
I'll have a look at it, if I could implement a limit for each rank, without messing too much around, as this could also be easily done by an additional script in a mission. Especially with the coming getter/setter functions for KP Ranks, so that content creators can easily access and manipulate the data.

By the way, here is a chart of the default point increase (rank * rank * 80)
![kpranksincrease](https://user-images.githubusercontent.com/3811977/43057597-90230fa4-8e43-11e8-8d7a-8f958f3f8c61.png)

You can also achieve your "limits" by adding offsets for the points for the range of the german "Unteroffiziere mit Portepee" and an additional one for the range of the officers.

Then you could add the offset points to a player who should be in this "career state" and from that point on he'll climb the ladder with the "usual points needed". Other players could still reach this, but due to the chosen offset it could take much more time to get all the needed points to get over this offset.

Example chart with the current increasing and an offset for the mentioned "career states":
![kpranksincreaseoffset](https://user-images.githubusercontent.com/3811977/43057738-36298bd0-8e44-11e8-891e-578bdb453881.png)
8 - 12 with an offset of 10,000 added
13 - 10 with an offset of 24,000 added

**Comment by Wyqer** [comment]
With the above offset possibility and the new getter/setter in 2.0.1, there won't be a "limitation" or "career" system implemented.
